#ifndef LAB_01_MODEL_ERRORS_HPP
#define LAB_01_MODEL_ERRORS_HPP

enum ERR_MODEL_PROXY
{
    ERR_MODEL_OKAY,
    ERR_MODEL_FILE_CANNOT_BE_OPENED,
    ERR_MODEL_FILE_INCOR,
    ERR_MODEL_ALLOC_FAILED,
    ERR_MODEL_IS_EMPTY,
    ERR_MODEL_INCOR_REQUEST,
    ERR_MODEL_FILE_NULL
};

#endif //LAB_01_MODEL_ERRORS_HPP
